kind: pipeline
name: testing
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: golang build
    image: golang:1.16
    environment:
      GO111MODULE: "on"
      GOPROXY: https://goproxy.cn,direct
    commands:
      - go get -v -t -d ./...
      - go build -v -ldflags '-X main.build=${DRONE_BUILD_NUMBER}' -a -o drone-plugin-ssh-publisher
  - name: docker build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ls
      - docker build -t ssh-pulisher-test .
      - docker images
  - name: testing
    image: ssh-pulisher-test
    settings:
      debug: true
      host:
        from_secret: host
      username:
        from_secret: username
      password:
        from_secret: password
      port:
        from_secret: port
      rm: true
      source:
        - ./ssh-pulisher-test
        - ./*
      target:
        - /usr/local/docker/ssh-test
      script:
        - cd /usr/local/docker/ssh-test
        - ls



volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock