kind: pipeline
name: testing
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: golang build
    image: golang:1.16
    environment:
      GO111MODULE: "on"
    commands:
      - go get -v -t -d ./...
      - go build -v -ldflags '-X main.build=${DRONE_BUILD_NUMBER}' -a -o drone-plugin-ssh-publisher
  - name: docker build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ls
      - docker build -t ssh-pulisher-test .


volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock