kind: pipeline
name: testing
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: testing
    image: hb0730/drone-plugin-ssh-publisher:0.0.1-beta
    settings:
      debug: true
      host:
        from_secret: host
      username:
        from_secret: username
      password:
        from_secret: password
      port:
        from_secret: port
      rm: true
      source:
        - ./ssh-pulisher-test
        - ./*
      target:
        - /usr/local/docker/ssh-test
      script:
        - cd /usr/local/docker/ssh-test
        - ls